#!/usr/bin/env python3
"""
Script to remove cut-in related content from ActionSummary-predict_explain-fsl-sys-En-cutin-time-paper-batch.py
Focus solely on ghost probing detection to avoid confusion and interference
"""

import re

def remove_cut_in_content():
    input_file = "/Users/wanmeng/repository/GPT4Video-cobra-auto/VIP/ActionSummary-predict_explain-fsl-sys-En-cutin-time-paper-batch.py"
    output_file = "/Users/wanmeng/repository/GPT4Video-cobra-auto/VIP/ActionSummary-predict_explain-fsl-sys-En-cutin-time-paper-batch-GHOST_ONLY.py"
    
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 修改Task 1标题，去除Cut-in提及
    content = content.replace(
        '**Task 1: Identify and Predict potential "Ghost Probing(专业术语：鬼探头)",Cut-in(加塞) etc behavior**',
        '**Task 1: Identify and Predict potential "Ghost Probing(专业术语：鬼探头)" behavior**'
    )
    
    # 去除Cut-in的整个定义段落（从"2) Cut-In(加塞):"到"***Key Note***"行结束）
    cut_in_section_pattern = r'2\) Cut-In\(加塞\):.*?Vehicles entering from a perpendicular road or from behind physical obstructions should never be labeled as "cut-in"\. These must be classified as "ghost probing" if they create a dangerous situation with minimal reaction time\.'
    content = re.sub(cut_in_section_pattern, '', content, flags=re.DOTALL)
    
    # 简化note内容，去除cut-in相关说明
    content = content.replace(
        'Note: Only those emerging from behind a physical obstruction can be considered as 鬼探头. Cut-in加塞 is different from 鬼探头.',
        'Note: Only those emerging from behind a physical obstruction can be considered as 鬼探头 (ghost probing).'
    )
    
    # 去除IMPORTANT DISTINCTION段落
    important_distinction_pattern = r'\*\*IMPORTANT DISTINCTION\*\*:.*?it must be classified as "ghost probing"\.'
    content = re.sub(important_distinction_pattern, '', content, flags=re.DOTALL)
    
    # 去除DEFINITIONS标题
    content = content.replace('DEFINITIONS:', '')
    
    # 修改key_actions要求，去除cut-in选项
    content = content.replace(
        '- `key_actions` must strictly adhere to the predefined categories:\n                        - ghost probing\n                        - cut-in\n                        - overtaking',
        '- `key_actions` must strictly adhere to the predefined categories:\n                        - ghost probing\n                        - overtaking'
    )
    
    # 去除cut-in示例
    content = content.replace(
        '- If there are multiple key actions, separate them by a comma, e.g. "ghost probing, cut-in".',
        '- Focus primarily on ghost probing detection for safety-critical analysis.'
    )
    
    # 修改示例中的key_actions选项
    content = content.replace(
        '"Select one or multiple categories from {{ghosting, cut-in, left/right-side vehicle overtaken, collision, none}}. If multiple categories apply, list them separatedly by commas. For cut-in, give detailed reasoning process!!!"',
        '"Select one or multiple categories from {{ghost probing, left/right-side vehicle overtaken, none}}. Focus primarily on accurate ghost probing detection."'
    )
    
    # 修改cut-in示例为ghost probing示例
    content = content.replace(
        '"key_actions": "cut-in: an object from an adjacent lane moves into the self-vehicle\'s lane at a distance too close to the observer"',
        '"key_actions": "ghost probing: an object suddenly emerges from behind a physical obstruction into the vehicle\'s path"'
    )
    
    # 去除cut-in惩罚机制，替换为ghost probing专注说明
    penalty_section_pattern = r'\*\*Penalty for Mislabeling\*\*:.*?the label will also be rejected\.'
    content = re.sub(penalty_section_pattern, 
        '**Focus on Ghost Probing Only**:\n                    - Prioritize accurate ghost probing detection over other behaviors.\n                    - Ghost probing must involve emergence from behind a physical obstruction.\n                    - If unsure whether a behavior qualifies as ghost probing, use "none" instead.',
        content, flags=re.DOTALL)
    
    # 清理多余的空行
    content = re.sub(r'\n\s*\n\s*\n', '\n\n', content)
    
    # 添加文件头注释说明
    header_comment = '''#!/usr/bin/env python3
"""
GHOST PROBING ONLY VERSION
Original file modified to focus solely on ghost probing detection.
All cut-in related content has been removed to avoid interference with ghost probing analysis.

Modifications:
1. Removed all cut-in definitions and examples
2. Simplified key_actions to focus on ghost probing
3. Removed cut-in classification logic
4. Updated prompts to prioritize ghost probing detection

Generated by: cut_in_removal_script.py
"""

'''
    
    # 替换原来的import开头
    content = re.sub(r'^import re', header_comment + 'import re', content)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✅ Cut-in content removed successfully!")
    print(f"📁 Original file: {input_file}")
    print(f"📁 Ghost-only file: {output_file}")
    print(f"📏 Original file size: {len(open(input_file, 'r', encoding='utf-8').read())} characters")
    print(f"📏 Modified file size: {len(content)} characters")
    print(f"📉 Size reduction: {len(open(input_file, 'r', encoding='utf-8').read()) - len(content)} characters")

if __name__ == "__main__":
    remove_cut_in_content()